steps:

  - label: Build Docker image
    command:
      - gcloud docker -- build --tag gcr.io/infolinks-gcr/slugger:${BUILDKITE_COMMIT} .
      - gcloud docker -- push gcr.io/infolinks-gcr/slugger:${BUILDKITE_COMMIT}
